{
    "data": [{
        "email": "bob@cedarhouse.co.za",
        "fname": "Bob",
        "lname": "Henderson",
        "created_at": "2016-08-08T20:48:33",
        "id": 1,
        "type": "teacher"
    }, {
        "email": "bob2@cedarhouse.co.za",
        "fname": "Bob",
        "lname": "Henderson",
        "created_at": "2016-08-09T01:04:55",
        "id": 3,
        "type": "teacher"
    }, {
        "email": "bob4@cedarhouse.co.za",
        "fname": "Bob",
        "lname": "Henderson",
        "created_at": "2016-08-09T01:05:16",
        "id": 4,
        "type": "teacher"
    }, {
        "email": "bob5@cedarhouse.co.za",
        "fname": "Bob",
        "lname": "Henderson",
        "created_at": "2016-08-09T16:15:03",
        "id": 8,
        "type": "teacher"
    }, {
        "email": "bob9@cedarhouse.co.za",
        "fname": "Bob",
        "lname": "Henderson",
        "created_at": "2016-08-09T19:54:17",
        "id": 9,
        "type": "teacher"
    }, {
        "email": "bob99@cedarhouse.co.za",
        "fname": "Bob",
        "lname": "Henderson",
        "created_at": "2016-08-09T19:55:09",
        "id": 11,
        "type": "teacher"
    }, {
        "email": "BenBon@cedarhouse.co.za",
        "fname": "Ben",
        "lname": "Henderson",
        "created_at": "2016-08-09T20:11:55",
        "id": 13,
        "type": "teacher"
    }, {
        "email": "fagit@r.u",
        "fname": "Ben",
        "lname": "Henderson",
        "created_at": "2016-08-09T20:48:54",
        "id": 15,
        "type": "teacher"
    }, {
        "email": "mysuperemail@cedarhouse.co.za",
        "fname": "Ben",
        "lname": "Henderson",
        "created_at": "2016-08-09T22:16:35",
        "id": 17,
        "type": "teacher"
    }, {
        "email": "5@cedarhouse.co.za",
        "fname": "Ben",
        "lname": "Henderson",
        "created_at": "2016-08-09T22:23:46",
        "id": 21,
        "type": "teacher"
    }, {
        "email": "asf@asd.dfg",
        "fname": "Ben",
        "lname": "Henderson",
        "created_at": "2016-08-09T22:26:16",
        "id": 22,
        "type": "teacher"
    }, {
        "email": "65@cedarhouse.co.za",
        "fname": "Ben",
        "lname": "Henderson",
        "created_at": "2016-08-09T22:28:30",
        "id": 23,
        "type": "teacher"
    }, {
        "email": "82@cedarhouse.co.za",
        "fname": "Ben",
        "lname": "Henderson",
        "created_at": "2016-08-09T22:38:18",
        "id": 24,
        "type": "teacher"
    }, {
        "email": "555@cedarhouse.co.za",
        "fname": "Ben",
        "lname": "Henderson",
        "created_at": "2016-08-10T01:10:47",
        "id": 26,
        "type": "teacher"
    }],
    "success": true
}
